name = "rustwasm-namnsdag"
type = "javascript"
workers_dev = true
compatibility_date = "2021-08-27"
account_id = ""

[vars]
WORKERS_RS_VERSION = "0.0.7"
SLACK_HOOK = ""
SLACK_URL = ""

[build]
command = "cargo install --path worker-build && worker-build --release"

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

[triggers]
crons = ["0 10 * * *"]
# crons = ["*/1 * * * *"]