[package]
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2018"
name = "worker-sandbox"
version = "0.1.0"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = ["console_error_panic_hook"]

[dependencies]
blake2 = "0.9.2"
chrono = { version = "0.4", default-features = false, features = ["wasmbind"]}
cloudflare = "0.8.7"
cfg-if = "0.1.2"
console_error_panic_hook = { version = "0.1.1", optional = true }
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4.3"
http = "0.2.4"
regex = "1.5.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wee_alloc = { version = "0.4.2", optional = true }
worker = { path = "../worker", version = "0.0.7" }

[dev-dependencies]
wasm-bindgen-test = "0.2"
